### ISSUE TITLE
Global variables not working

### ISSUE THREAD

**Issue by harrisonratcliffe** [phprouter/router_xss_csrf#22]
I see someone else opened an issue about this, but I am also having issues with global variables.

I am also having issues with global variables. Can you show code as an example that it works @phprouter ?
**Code:**
```
$testVar = "testing";

function globVar() {
    global $testVar;
    echo $testVar;
}

globVar(); 
```
**Output of `var_dump($GLOBALS['testVar']);`:**
`NULL`

The above code works absolutely fine if I am not using the router.

**Comment by phprouter** [comment]
Are you sure this has something to do with PhpRouter?

**Comment by harrisonratcliffe** [comment]
I've tried on a completely fresh PHP application and it's the same on Caddy, NGINX, and Apache.

**Comment by santiagodonoso** [comment]
I don't see any issues with PhpRouter and the global variables.

**Comment by phprouter** [comment]
No issues with global varaibles.

**Comment by aj-potc** [comment]
There are indeed issues with global variables due to the way PHP Router uses the `include()` function.

When a file is included within a function, it executes in the local scope of that function. This means it doesn’t automatically have access to global variables unless they are declared as global inside that function.
Counterintuitively, even if the global variables are defined **later** in the script (after the routing has happened), the function’s local scope at the time of inclusion is what matters.

This means you need to explicitly define all global variables inside the `route()` function in order to use them later. Here is an example:

```
function route($route, $path_to_include) {
    // Make the global variables available in this function's scope
    global $log_dir, $log_file;

    // Include the file
    include_once $path_to_include;
}
```
